import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          Check out the profiles !!
          <Link href={"/profiles/bob"}>1. Bob</Link>
          <Link href={"/profiles/max"}>2. Max</Link>
          <Link href={"/profiles/brian"}>3. Brian</Link>
      </main>
    </div>
  )
}

export default Home
